// @baseUrl = http://98.71.87.121
@baseUrl = http://localhost:3001

### send GET request to /counter-allowedmax
GET {{baseUrl}}/counter HTTP/1.1

### Send GET request to the /counter-endpoint
//GET {{baseUrl}}/api/counter-reset/ HTTP/1.1
GET {{baseUrl}}/counter-reset/ HTTP/1.1


### Send POST request to '/counter' endpoint
POST {{baseUrl}}/counter/ HTTP/1.1
// POST {{baseUrl}}/api/counter/ HTTP/1.1
Content-Type: application/json

{
    "countIn": 3,
    "countOut": 1
}

###
POST {{baseUrl}}/change-max/ HTTP/1.1
// POST {{baseUrl}}/api/counter/ HTTP/1.1
Content-Type: application/json

{
    "max": "28"
}
